version: "3.9"

services:
  distributed-store:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    # No host port mapping here to allow scaling
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  nginx:
    image: nginx:latest
    ports:
      - "8080:80" # Only the load balancer exposes a port to the host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - distributed-store
