version: "3.9"
services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - NODE_ID=1
      - AIR_TMP_DIR=tmp-node1

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - NODE_ID=2
      - AIR_TMP_DIR=tmp-node2

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - NODE_ID=3
      - AIR_TMP_DIR=tmp-node3

  nginx:
    image: nginx:latest
    ports:
      - "8080:80" # Only the load balancer exposes a port to the host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node1 # Corrected dependency: node1
      - node2 # Corrected dependency: node2
      - node3 # Corrected dependency: node3
